# -*- coding: utf-8 -*-
"""DL_Assignment2_partB.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ME2tVUHHcNRIGIU9uHuWnHa3a0wmgu5j

# Finetune with LLaMA Factory

Please use a **free** Tesla T4 Colab GPU to run this!

Project homepage: https://github.com/hiyouga/LLaMA-Factory

## Install Dependencies
"""

# Commented out IPython magic to ensure Python compatibility.
# 1. 先卸载依赖冲突
!pip uninstall thinc -y
!pip uninstall gcsfs -y
# %cd /content/
# %rm -rf LLaMA-Factory
!git clone --depth 1 https://github.com/hiyouga/LLaMA-Factory.git
# %cd LLaMA-Factory
# %ls
!pip install -e .[torch,bitsandbytes] -qU
!pip install numpy==1.26.4 --force-reinstall --no-deps

"""### Check GPU environment"""

import torch
try:
  assert torch.cuda.is_available() is True
except AssertionError:
  print("Please set up a GPU before using LLaMA Factory: https://medium.com/mlearning-ai/training-yolov4-on-google-colab-316f8fff99c6")

"""## Update Identity Dataset"""

from datasets import load_dataset

# 1. 加载原始数据集
dataset = load_dataset(
    "ShengbinYue/DISC-Law-SFT",
    data_files="DISC-Law-SFT-Triplet-QA-released.jsonl"
)

# 2. 定义Alpaca格式转换函数
def convert_to_alpaca(batch_examples):
    return {
        # 为整个批次生成指令列表
        "instruction": ["根据中国法律知识回答以下问题"] * len(batch_examples["input"]),
        "input": batch_examples["input"],  # 直接传递批次输入
        "output": batch_examples["output"]
    }
# 3. 转换并清理字段
# 定义需要保留的列
keep_columns = ["instruction", "input", "output"]

# 执行转换（批处理提升效率）
dataset = dataset.map(
    convert_to_alpaca,
    batched=True,
    batch_size=1000,
    remove_columns=["id", "reference"]  # 显式删除多余字段
)

# 4. 分割数据集（90%训练，10%测试）
dataset = dataset["train"].train_test_split(test_size=0.1, seed=42)

# 5. 保存到LLaMA Factory数据目录
# 正确保存方式（移除encoding参数）
dataset.save_to_disk("/content/LLaMA-Factory/data/disc_law_sft")

from datasets import load_from_disk

# 加载保存的数据集
dataset = load_from_disk("/content/LLaMA-Factory/data/disc_law_sft")

# 验证中文编码
# 定义美化打印函数
def pretty_print_example(example, index=0):
    text = f"""
    {'='*40}
    [示例 {index + 1}]
    {'-'*40}
    instruction:
    {example['instruction']}

    input:
    {example['input']}

    output:
    {example['output']}
    {'='*40}
    """
    print(text.expandtabs(4))  # 自动缩进

# 打印前3个示例
for idx in range(1):
    pretty_print_example(dataset["train"][idx], idx)

"""## Fine-tune model via Command Line"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/LLaMA-Factory/
import json

args = dict(
  stage="sft",                                               # do supervised fine-tuning
  do_train=True,
  model_name_or_path="Qwen/Qwen2.5-7B-Instruct",             # use bnb-4bit-quantized Llama-3-8B-Instruct model
  # tokenizer_name_or_path="Qwen/Qwen2.5-7B-Instruct",  # 显式指向 Qwen Tokenizer
  dataset="disc_law_sft",                                    # use alpaca and identity datasets
  template="chatml",                                         # use llama3 prompt template
  finetuning_type="lora",                                    # use LoRA adapters to save memory
  lora_target="c_attn,q_proj,v_proj",                        # attach LoRA adapters to all linear layers
  output_dir="llama3_lora_law",                              # the path to save LoRA adapters
  per_device_train_batch_size=4,                             # the micro batch size
  gradient_accumulation_steps=4,                             # the gradient accumulation steps
  lr_scheduler_type="cosine",                                # use cosine learning rate scheduler
  logging_steps=5,                                           # log every 5 steps
  warmup_ratio=0.1,                                          # use warmup scheduler
  save_steps=100,                                           # save checkpoint every 1000 steps
  learning_rate=3e-5,                                        # the learning rate
  num_train_epochs=0.05,                                      # the epochs of training
  max_samples=None,                                           # use 500 examples in each dataset
  max_grad_norm=1.0,                                         # clip gradient norm to 1.0
  loraplus_lr_ratio=16,                                    # use LoRA+ algorithm with lambda=16.0
  fp16=True,                                                 # use float16 mixed precision training
  report_to="none",                                          # disable wandb logging
  quantization_bit=4,
  # use_flash_attention_2=True
)

json.dump(args, open("train_llama3.json", "w", encoding="utf-8"), indent=2)


!rm -rf /content/llama3_lora_law/*

!llamafactory-cli train train_llama3.json

"""## Infer the fine-tuned model"""

# Commented out IPython magic to ensure Python compatibility.
from llamafactory.chat import ChatModel
from llamafactory.extras.misc import torch_gc

# %cd /content/LLaMA-Factory/

args = dict(
  model_name_or_path="Qwen/Qwen2.5-7B-Instruct",         # use bnb-4bit-quantized Llama-3-8B-Instruct model
  adapter_name_or_path="llama3_lora_law",                        # load the saved LoRA adapters
  template="chatml",                                         # same to the one in training
  finetuning_type="lora",                                    # same to the one in training
)
chat_model = ChatModel(args)

torch_gc()

from datasets import load_from_disk
import random
from tabulate import tabulate

try:
    dataset = load_from_disk("/content/LLaMA-Factory/data/disc_law_sft")
    test_dataset = dataset["test"]
except Exception as e:
    print(f"数据集加载失败：{str(e)}")
    exit()

random.seed(42)
sampled_indices = random.sample(range(len(test_dataset)), 5)
samples = [test_dataset[i] for i in sampled_indices]

def model_inference(question: str) -> str:
    """包装现有的聊天模型接口"""
    messages = [{"role": "user", "content": question}]
    response = ""
    try:
        for new_text in chat_model.stream_chat(messages):
            response += new_text
    except Exception as e:
        response = f"推理错误：{str(e)}"
    return response

table_data = []
for idx, sample in enumerate(samples, 1):
    pred_answer = model_inference(sample["input"])

    table_row = [
        f"案例 {idx}",
        sample["input"].split("<问题>")[-1].strip(),
        pred_answer,
        sample["output"]
    ]
    table_data.append(table_row)

headers = ["ID", "法律问题", "模型回答", "参考答案"]
print("\n" + "="*80)
print(f"{'法律问答测试结果对比':^80}")
print("="*80)
print(tabulate(table_data,
             headers=headers,
             tablefmt="grid",
             maxcolwidths=[None, 30, 40, 40],
             stralign="left",
             numalign="center"))

import pandas as pd
import matplotlib.pyplot as plt

# 读取日志
log_path = "/content/LLaMA-Factory/llama3_lora_law/trainer_log.jsonl"
logs = pd.read_json(log_path, lines=True)

print(logs.head())

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime

# ================== 1. 数据加载与预处理 ==================
# 正确读取JSON Lines格式日志
log_path = "/content/LLaMA-Factory/llama3_lora_law/trainer_log.jsonl"
logs = pd.read_json(log_path, lines=True)

# 时间数据转换
logs['elapsed_time'] = pd.to_datetime(logs['elapsed_time'])
logs['remaining_time'] = pd.to_datetime(logs['remaining_time'])

# 计算相对时间（小时）
logs['elapsed_hours'] = (logs['elapsed_time'] - logs['elapsed_time'].min()).dt.total_seconds()/3600
logs['remaining_hours'] = (logs['remaining_time'] - logs['remaining_time'].min()).dt.total_seconds()/3600

# ================== 2. 可视化样式配置 ==================
plt.style.use('seaborn-v0_8-dark')
palette = sns.color_palette("husl", 4)
fig, axs = plt.subplots(3, 1, figsize=(12, 15), dpi=150)

# ================== 3. 训练损失曲线 ==================
sns.lineplot(x='current_steps', y='loss', data=logs,
             color=palette[0], linewidth=2, marker='o', markersize=6, ax=axs[0])
axs[0].set_title('Training Loss Progression', fontsize=14, pad=15)
axs[0].set_xlabel('Training Steps', fontsize=12)
axs[0].set_ylabel('Loss Value', fontsize=12)
axs[0].fill_between(logs['current_steps'], logs['loss'], alpha=0.2, color=palette[0])

# ================== 4. 学习率变化曲线 ==================
sns.lineplot(x='current_steps', y='lr', data=logs,
             color=palette[1], linewidth=2, ax=axs[1])
axs[1].set_title('Learning Rate Schedule', fontsize=14, pad=15)
axs[1].set_xlabel('Training Steps', fontsize=12)
axs[1].set_ylabel('Learning Rate', fontsize=12)
axs[1].set_yscale('log')  # 对数坐标更清晰显示变化

# ================== 5. 训练进度可视化 ==================
# 进度曲线
sns.lineplot(x='current_steps', y='percentage', data=logs,
            color=palette[2], linewidth=2, label='Progress', ax=axs[2])

# 时间预测填充
axs[2].fill_between(logs['current_steps'],
                   logs['percentage'],
                   alpha=0.2, color=palette[3])

# 添加时间标注
for idx in [0, len(logs)//2, -1]:
    axs[2].annotate(
        f"{logs['percentage'].iloc[idx]:.1f}%\n" +
        datetime.strftime(logs['elapsed_time'].iloc[idx], "%m-%d %H:%M"),
        xy=(logs['current_steps'].iloc[idx], logs['percentage'].iloc[idx]),
        xytext=(0, 15), textcoords='offset points',
        arrowprops=dict(arrowstyle="->", color='gray'),
        fontsize=9
    )

axs[2].set_title('Training Progress & Time Estimation', fontsize=14, pad=15)
axs[2].set_xlabel('Training Steps', fontsize=12)
axs[2].set_ylabel('Completion (%)', fontsize=12)
axs[2].set_ylim(0, 100)

# ================== 6. 全局优化与保存 ==================
plt.tight_layout(pad=3.0)
plt.suptitle('LLaMA-3 Legal Domain Fine-tuning Metrics', y=1.02, fontsize=16)
plt.savefig('training_metrics.png', bbox_inches='tight', dpi=300)
plt.show()

"""## Merge the LoRA adapter and optionally upload model

NOTE: the Colab free version has merely 12GB RAM, where merging LoRA of a 8B model needs at least 18GB RAM, thus you **cannot** perform it in the free version.
"""

!huggingface-cli login

# Commented out IPython magic to ensure Python compatibility.
import json

args = dict(
  model_name_or_path="Qwen/Qwen2.5-7B-Instruct",   # use official non-quantized Llama-3-8B-Instruct model
  adapter_name_or_path="llama3_lora_law",                       # load the saved LoRA adapters
  template="chinese_law",                                        # same to the one in training
  finetuning_type="lora",                                   # same to the one in training
  export_dir="llama3_lora_law_merged",                          # the path to save the merged model
  export_size=2,                                            # the file shard size (in GB) of the merged model
  export_device="auto",                                      # the device used in export, can be chosen from `cpu` and `auto`
  export_hub_model_id="jimchoi/Qwen2.5-7B-Instruct_DISC_Law_SFT",               # the Hugging Face hub ID to upload model
)

json.dump(args, open("merge_llama3.json", "w", encoding="utf-8"), indent=2)

# %cd /content/LLaMA-Factory/

!llamafactory-cli export merge_llama3.json

# 2. 压缩整个工作区（排除缓存文件）
!zip -r /content/src.zip /content/LLaMA-Factory/src

files.download("/content/src.zip")